### ISSUE TITLE
Bootstrap align issue

### ISSUE THREAD

**Issue by Rolando-Barbella** [mervick/material-design-icons#2]
Hi, thanks for doing this, I just started getting into material design, my project already has a lot of bootstrap but I'm hoping both tools can get alone with out that many issues.

So the problem is: the icons don't seem to align well when I place text next to it while font awesone still does a good job in that sence.
## Material design example 

``` html
 <ul class="sidebar-menu">
      <li class="active">
            <a href="#">
                <i class="mdi mdi-attachment mdi-2x"></i> <span>Click</span>
              </a>
            </li>
      <li> 
<ul/>
```
## Font awesone example 

``` html
<ul class="sidebar-menu">
      <li class="active">
            <a href="#">
                <i class="fa-paperclip fa-2x"></i> <span>Click</span>
              </a>
            </li>
      <li> 
<ul/>
```

Any ideas??
Thanks

**Comment by mervick** [comment]
I suspect that you are using some of the stylesheets that assigned to `.fa` but ignored for `.mdi`. You can check this by looking in the chrome element inspector or in the firefox firebug

**Comment by Rolando-Barbella** [comment]
I did a plunk were you can see the issue, it has to do with the original project, not with your version, I guess I can change  the css and fixed somehow but I wanted to know if there is a more practical solution.

Thank you

https://plnkr.co/edit/QSPpQbzUgLzbR4gsAV0w?p=preview

**Comment by Rolando-Barbella** [comment]
There is an open issue here https://github.com/google/material-design-icons/issues/206
indeed you have to fixed your self 

Thanks any way

**Comment by mervick** [comment]
I think that this is some kind of bug in the fonts associated with the baseline.
