### ISSUE TITLE
This repository is it always maintened ?

### ISSUE THREAD

**Issue by kevincaradant** [mervick/material-design-icons#4]
Hi

Do you update your repo to have the latest icons with google material design ?

It's perfect your reposiroty.

Thank you

**Comment by mervick** [comment]
Hi, thanks,
Yes icons are latest, the same as in official repo.

**Comment by kevincaradant** [comment]
OK :)

Is it possible to load network social like linkedin, facebook, github etc or not ? I know in the google material icons, there are some troubles of rights, so if it's possible to use "fa" like here, that will be perfect .
http://mdbootstrap.com/css/icons-list/.

Maybe it's not possible, I don't know. Thanks

**Comment by mervick** [comment]
Sorry, I am don't understand what are you mean, 
can are you explain me a little more?

**Comment by kevincaradant** [comment]
In fact, I want material design icons and also the social network icons. If you search "github", "linkedIn", "Facebook", "Twitter" etc. There are not exists for the moment in Google Material Design icons , a history around the trademark. I see Bootstrap MaterialDesign use also fontawesome "fa". So for the moment I have to load fontawesome for social network icons and your library for the others icons. 
I asked if just with your  library I could load both without have to load two different libraries ;)

**Comment by mervick** [comment]
Ok, I understand your point, 
in this repository, I did not add any icons except official.
To be honest, all I've done is add some styles for the convenience,
so I don't planned add any extra icons

**Comment by kevincaradant** [comment]
OK no problem, I will continue like that until the new icons in Google material.
Thanks ;)
