### ISSUE TITLE
LICENSE outdated

### ISSUE THREAD

**Issue by SBejga** [mervick/material-design-icons#5]
Hi,

I just found that the LICENSE information is outdated. At http://mervick.github.io/material-design-icons/ and in README there is written, Google is using CC-BY-4.0. But as of today, Google is using Apache License. This might have changed.

The LICENSE information should be updated then. Shall I create a PR?

**Comment by mervick** [comment]
It still uses old fonts from 2.2.0 version, so if you want change license it also require to update fonts, codepoints and generate css files and demo using gulp and grunt tasks.
Only update license without these changes will be insufficient.
If you want you can create PR with all of that.

**Comment by SBejga** [comment]
Ah I understand. With version 3.0 they have changed license to Apache-2.0. If I find some time I will try to create a PR.

Thanks for your fast reply.
