### ISSUE TITLE
I would like to contribute adding some icons

### ISSUE THREAD

**Issue by darkman97i** [mervick/material-design-icons#7]
It is not clear for me how doing it if you can share some clues maybe I can do without mistakes. For example, I would like to add file_copy
![Selección_032](https://user-images.githubusercontent.com/958703/104901614-e902f000-597d-11eb-848b-532cc21a9282.png)

**Comment by mervick** [comment]
Hello. It uses https://github.com/google/material-design-icons and shell script to generate icons.
It require some modifications due to changes on google repo.
I will do this today

**Comment by darkman97i** [comment]
thanks, if I can help in some manner please tell me.

**Comment by mervick** [comment]
I updated fonts and icons to the latest version.
But unfortunately I still not updated demo page.

For installation look at [README](https://github.com/mervick/material-design-icons#installation)
I published to the new repo on npm due to unstable work of npmjs.com (I just could not login in my account, so I created a new one)

**Comment by darkman97i** [comment]
Thanks for the update. I have done a quick test from my side and only I found a few problems:

![Selección_037](https://user-images.githubusercontent.com/958703/105030252-d1963680-5a53-11eb-8a1e-ee437a2cf5ac.png)

List of what are not working:
* mdi-battery
* mdi-battery-charging
* mdi-content-copy
* mdi-content-cut
* mdi-content-paste

This is the sample file I used for testing all icons, maybe will have some use to you.
[mdi.txt](https://github.com/mervick/material-design-icons/files/5835909/mdi.txt)

**Comment by mervick** [comment]
There are no such icons in the Google Material Icons fonts.
To be clear this repo uses Google Material Icons fonts.

https://material.io/resources/icons/

**Comment by darkman97i** [comment]
The list of icons are in Google material icons:
![Selección_038](https://user-images.githubusercontent.com/958703/105141422-6a32c200-5af9-11eb-8d4c-b047fc24755b.png)

Really, I generated the icon list from your material-icons-base.css file
![Selección_039](https://user-images.githubusercontent.com/958703/105141737-ec22eb00-5af9-11eb-9457-1dddfb4d3f16.png)

I ignore why these 5 icons are not working ... maybe an issue with the latest google release.

**Comment by mervick** [comment]
It's not very clear but some icons no exists in all Material fonts, some icons do exists only in certain fonts (themes).  
`mdi-content-copy`, `mdi-content-cut` and `mdi-content-paste` does not exists in `Material Icons` font but it is in `Material Icons Outlined`.
You can use it with loaded outlined font by using classes `mdi-outlined mdi-content-copy`,  `mdi-outlined mdi-content-cut` and `mdi-outlined mdi-content-paste`.

I will update demo with all themes.

**Comment by darkman97i** [comment]
As explained works perfect, thanks for your time.
